### ISSUE TITLE
Unavailable mirror leads to stale version for master

### ISSUE THREAD

**Issue by linusg** [mlugg/setup-zig#9]
> If you've experienced issues with a default mirror, please open an issue, and I will communicate with the mirror's owner or remove it from the list.

It appears that `zigmirror.hryx.net` is unavailable, and the fallback of `pkg.machengine.org` leads to an old version of zig being installed (`0.14.0-dev.855+de1fb1990`) despite `version: master`. A previous working run gave me `0.14.0-dev.1550`.

```
::warning::Failed to restore: getCacheEntry failed: Cache Service Url not found, unable to restore cache.
Cache miss. Fetching Zig 0.14.0-dev.855+de1fb1990
Attempting mirror: https://zigmirror.hryx.net/zig
Unexpected HTTP response: 502
Waiting 14 seconds before trying again
Unexpected HTTP response: 502
Waiting 15 seconds before trying again
Mirror failed with error: Error: Unexpected HTTP response: 502
Attempting mirror: https://pkg.machengine.org/zig
[command]/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /workspace/kiesel-js/kiesel --files-from manifest.txt --use-compress-program zstdmt
::warning::Failed to save: reserveCache failed: Cache Service Url not found, unable to restore cache.
Extracting tarball zig-linux-x86_64-0.14.0-dev.855+de1fb1990.tar.xz
```

**Comment by mlugg** [comment]
Ah, one of your runs had slightly unfortunate timing! We just today completed our migration of https://ziglang.org/ to an implementation based on [Zine](https://zine-ssg.io/), and during that transition, a small error was made which caused the `index.json` data to be out-of-date for about 10 minutes. Any runs targeting Zig master which were triggered in that interval will have either failed to fetch, or will have fetched an outdated version.

All this to say... blame upstream :^)

**Comment by linusg** [comment]
Fascinating, thanks for looking into it!
